### ISSUE TITLE
Nested objects do not work

### ISSUE THREAD

**Issue by mirzawaqasahmed** [operatingops/terraform_external_data#17]
Hi,
I am trying to find a way to return a nested dictionary which isn't working. This is my code.

`terraform.tf`

```
provider "external" {
  version = "~> 1.2"
}

data "external" "vip_config" {
  program = ["python", "${path.module}/f5-terraform-ext-data.py"]

}

output "output_all_result_data" {
  value = data.external.vip_config.result
}
```

`f5-terraform-ext-data.py`

```
@terraform_external_data
def f5_ext_data(tf_query):

    tf_query.update({"name": "pool1"})

    return tf_query


if __name__ == '__main__':
    f5_ext_data()
```

The above works and gives me something like:

```
output_all_result_data = {
  "name": "pool1"
}
```

However what I am looking at it is a way to get a more nested dictionary. Like below:

```
{"pool":[{"name":"pool1"},{"name":"pool2"}]}
```

When I return this Data it doesn't work. It errors out as:

`Error: failed to execute "python": Values must be strings.`

Any suggestion how to make it work? I can make it work in Python, but it doesn't work with the data provider. Terraform gives me errors.

Thanks in advance.

**Comment by operatingops** [comment]
Hey @mirzawaqasahmed,

That `Values must be strings` error is coming from a validator I built into the module. It's there because the external program protocol spec [requires the maps to have all string values](https://www.terraform.io/docs/providers/external/data_source.html#external-program-protocol).

Nested maps weren't supported at all until the recent terraform 0.12 release, and I suspect that's the reason behind this requirement. When I upgraded this to work with 0.12, I rechecked the protocol spec hoping they'd have updated it to allow nested maps, but it still says values have to be strings. Hopefully they'll eventually change the spec.

I've hit this in the past and I've seen a couple alternative that might be worth looking at:

One is adding the [`query` argument](https://github.com/operatingops/terraform_external_data#example-usage) to pass in the index of the pool you want to look up, then use that in the python function to pull that pool's name and return it in a flat map like `{"name": "pool_name"}`.

Another is to just tweak the map to make it work like a list. A little funky, but functional:

```
{
    "1": "name_of_pool_1",
    "2": "name_of_pool_2"
}
```

Hope that helps!
